<template>
    <svg height="200px" preserveAspectRatio="xMidYMid"
         style="margin: auto; display: block; shape-rendering: auto;" viewBox="0 0 100 100" width="200px"
         xmlns="http://www.w3.org/2000/svg"
         xmlns:xlink="http://www.w3.org/1999/xlink">
        <g transform="translate(50 50) scale(0.7000000000000001) translate(-50 -50)">
            <g>
                <animateTransform attributeName="transform" calcMode="spline" dur="4s"
                                  keySplines="0 1 0 1;0 1 0 1;0 1 0 1;0 1 0 1"
                                  keyTimes="0;0.25;0.5;0.75;1" repeatCount="indefinite"
                                  type="rotate"
                                  values="0 50 50;90 50 50;180 50 50;270 50 50;360 50 50"></animateTransform>
                <g>
                    <animateTransform attributeName="transform" calcMode="spline" dur="1s" keySplines="1 0 0 1;1 0 0 1"
                                      keyTimes="0;0.5;1" repeatCount="indefinite" type="scale"
                                      values="1;1;0.5"></animateTransform>
                    <g transform="translate(25 25)">
                        <rect fill="#f2dcc2" height="52" width="52" x="-25" y="-25">

                            <animate attributeName="fill" calcMode="spline" dur="4s"
                                     keySplines="0 1 0 1;0 1 0 1;0 1 0 1;0 1 0 1"
                                     keyTimes="0;0.25;0.5;0.75;1" repeatCount="indefinite"
                                     values="#f2dcc2;#d9a171;#bf8563;#d9c1c1;#f2dcc2"></animate>
                        </rect>
                    </g>
                    <g transform="translate(25 75)">
                        <rect fill="#f2dcc2" height="50" width="52" x="-25" y="-25">
                            <animateTransform attributeName="transform" calcMode="spline" dur="1s"
                                              keySplines="1 0 0 1;1 0 0 1"
                                              keyTimes="0;0.5;1" repeatCount="indefinite" type="scale"
                                              values="0;1;1"></animateTransform>
                            <animate attributeName="fill" calcMode="spline" dur="4s"
                                     keySplines="0 1 0 1;0 1 0 1;0 1 0 1;0 1 0 1"
                                     keyTimes="0;0.25;0.5;0.75;1" repeatCount="indefinite"
                                     values="#f2dcc2;#d9a171;#bf8563;#d9c1c1;#f2dcc2"></animate>
                        </rect>
                    </g>
                    <g transform="translate(75 25)">
                        <rect fill="#f2dcc2" height="52" width="50" x="-25" y="-25">
                            <animateTransform attributeName="transform" calcMode="spline" dur="1s"
                                              keySplines="1 0 0 1;1 0 0 1"
                                              keyTimes="0;0.5;1" repeatCount="indefinite" type="scale"
                                              values="0;1;1"></animateTransform>
                            <animate attributeName="fill" calcMode="spline" dur="4s"
                                     keySplines="0 1 0 1;0 1 0 1;0 1 0 1;0 1 0 1"
                                     keyTimes="0;0.25;0.5;0.75;1" repeatCount="indefinite"
                                     values="#f2dcc2;#d9a171;#bf8563;#d9c1c1;#f2dcc2"></animate>
                        </rect>
                    </g>
                    <g transform="translate(75 75)">
                        <rect fill="#f2dcc2" height="50" width="50" x="-25" y="-25">
                            <animateTransform attributeName="transform" calcMode="spline" dur="1s"
                                              keySplines="1 0 0 1;1 0 0 1"
                                              keyTimes="0;0.5;1" repeatCount="indefinite" type="scale"
                                              values="0;1;1"></animateTransform>
                            <animate attributeName="fill" calcMode="spline" dur="4s"
                                     keySplines="0 1 0 1;0 1 0 1;0 1 0 1;0 1 0 1"
                                     keyTimes="0;0.25;0.5;0.75;1" repeatCount="indefinite"
                                     values="#f2dcc2;#d9a171;#bf8563;#d9c1c1;#f2dcc2"></animate>
                        </rect>
                    </g>
                </g>
            </g>
        </g>
        <!-- [ldio] generated by https://loading.io/ --></svg>
</template>

<script>
export default {
    name: "SpinnerComponent"
}
</script>
